### ISSUE TITLE
Days option is not working with HA

### ISSUE THREAD

**Issue by phoniclynx** [safepay/sensor.willyweather#1]
When i put the config in for the WW card I get the error

>>> Configuration validation
Validate your configuration if you recently made some changes to your configuration and want to make sure that it is all valid
Configuration invalid
Invalid config for [sensor.willyweather]: [days] is an invalid option for [sensor.willyweather]. Check: sensor.willyweather->days. (See ?, line ?). Please check the docs at https://home-assistant.io/components/sensor.willyweather/
>>>

**Comment by safepay** [comment]
forecast_days:

is the config option
