### ISSUE TITLE
Request: Access to forecast Wind

### ISSUE THREAD

**Issue by tgcowell** [safepay/sensor.willyweather#10]
Hi Mate,

Happy to explore this if you would like? But I’d love to be able to include forecast data for wind. Then create automations based on that data. It’s a great help knowing this for when scheduling a boat trip. 

I appreciate it would require additional data from the API... but not knowing where to start would appreciate some assistance if possible? Otherwise brilliant plug-in love it!

Cheers
Tim

**Comment by safepay** [comment]
Hi Tim,

This is a bit challenging as the API data for wind is different for the other sensors. It has multiple values per day, whereas values for temperature and rain have single values and are really easy to handle.

Have a look at the API docs and you will see what I mean.
https://www.willyweather.com.au/api/docs/v2.html

You may need to separate handling just for this case.

**Comment by tgcowell** [comment]
Thank you for your reply, I've tried to make a little sense but think it goes above my ability at the moment.

Will keep researching and see what I can come up with 👍

On a side note I think 0.116 has broken the integration, there was some mention of custom cards breaking.

Cheers
Tim
