### ISSUE TITLE
How are weather states mapped?

### ISSUE THREAD

**Issue by sddgit** [safepay/sensor.willyweather#13]
I'd like to use tomorrow's weather forecast to decide whether to run my pool system and heater overnight if there won’t be enough sun to run it using solar generation tomorrow. Any ideas what would be the best way to do this? Should I use the icon description in the sensors, or the summary text? What are all their possible values? And is the WillyWeather information mapped to the standard HA icons somehow?

Really appreciate any help...

**Comment by safepay** [comment]
You can get tommorow's temp using this template, for example:
```
{{ state_attr('weather.your_location', 'forecast')[1].temperature }}
```

Set your_location to the name of your actual location.

The "1" means tomorrow (0, today, etc)

Hope this helps

**Comment by sddgit** [comment]
Thanks for helping out. That template will be handy. Haven’t quite got into those yet!

Unfortunately, just the temperature won’t help me decide whether my solar panels will be generating enough power to run and heat the pool. I was thinking of using the icon description and summary description fields in the individual sensors to come up with some sort of approximation. But I can’t find a list of possible values for those. And they don’t seem to correspond to the WillyWeather api field descriptions either.

**Comment by safepay** [comment]
You are probably better asking in the forums, as the issues section here is for actual issues, rather than general questions. So I 'll close this issue.

But all you have available in HA are the attributes that you can see in the sensor.

The "condition" is how HA sets the icon. Rainy = clouds, etc.

What you really want is to use SolCast.
See https://community.home-assistant.io/t/rest-api-command-platform-fails-on-post-to-external-url-solcast/143238/135?u=safepay

**Comment by sddgit** [comment]
Ok, fair enough. Is it possible, though, to get a list of possible values for the icon and summary fields from somewhere?

Thanks for the heads up on Solcast. I had seen the Forecast.Solar integration, but that service didn’t seem to cover Australia.

**Comment by safepay** [comment]
It's in the code for the weather sensor:

Left side is WW, right side HA.

```
MAP_CONDITION = {
'fine' : 'sunny',
'mostly-fine' : 'sunny',
'high-cloud' : 'partlycloudy',
'partly-cloudy' : 'partlycloudy',
'mostly-cloudy' : 'cloudy',
'cloudy' : 'cloudy',
'overcast' : 'cloudy',
'shower-or-two' : 'rainy',
'chance-shower-fine' : 'rainy',
'chance-shower-cloud' : 'rainy',
'drizzle' : 'rainy',
'few-showers' : 'rainy',
'showers-rain' : 'rainy',
'heavy-showers-rain' : 'pouring',
'chance-thunderstorm-fine' : 'lightning',
'chance-thunderstorm-cloud' : 'lightning',
'chance-thunderstorm-showers' :  'lightning-rainy',
'thunderstorm' : 'lightning-rainy',
'chance-snow-fine' : 'snowy',
'chance-snow-cloud' : 'snowy',
'snow-and-rain' : 'snowy-rainy',
'light-snow' : 'snowy',
'snow' : 'snowy',
'heavy-snow' : 'snowy',
'wind' : 'windy',
'frost' : 'clear-night',
'fog' : 'fog',
'hail' : 'hail',
'dust' : 'exceptional'
}
```

**Comment by sddgit** [comment]
Thanks very much for taking the time to do that. I’m very new to HA, so I’ll have to hunt for the code for the sensors.

I’m still a bit confused by the difference between the representations in ww and the bom integration, given they’re from the same data source. For instance, for next Tuesday, the ww sensor for icon description says rainy, and bom’s says showers. Maybe they’ve picked a lightly different weather station, or ww just maps differently.

I’m investigating solcast, and I hope that will work much better for my use case. Thanks for your input to that!

**Comment by sddgit** [comment]
There is one more little query regarding the icons. In the ww sensor for icon, I see text that isn’t in the above mapping, like clear-day. Where does that text come from?

**Comment by safepay** [comment]
> In the ww sensor for icon

Sorry, but I don't understand the question.

But HA has a small list of icons. "clear-day" doesn't exist.

You can see what is available under "Personal Icons" on this page: https://www.home-assistant.io/lovelace/weather-forecast/

**Comment by sddgit** [comment]
Apologies. I’ll try to make myself a little clearer. There is a ww sensor called, for example, `sensor.ww_day_1_icon`. This can contain values, like “clear-day”, that don’t seem to match up with either the ww service or the HA icons. I’ve attached a screenshot of the contents of some sensors in ww and the bom integration. Thanks for sticking with me…
![10F52DC3-FC5E-439D-85D6-B145E710B28A](https://user-images.githubusercontent.com/76281052/133865280-5d69278b-77fa-4d22-b38e-f730010b7f62.jpeg)

**Comment by sddgit** [comment]
Ah, I can see from the code that the icon sensor is populated using the Dark Sky terminology. Query solved! Thanks again.
