### ISSUE TITLE
Where is the plugin in HACS

### ISSUE THREAD

**Issue by ilium007** [safepay/sensor.willyweather#14]
I am searching HACS but can't find the integration. Is it still available?

**Comment by safepay** [comment]
Just search for "Willy".

**Comment by ilium007** [comment]
<img width="703" alt="image" src="https://user-images.githubusercontent.com/732766/133911835-340da78c-b7d5-4102-a1e4-2269bcdfcff6.png">

**Comment by safepay** [comment]
You are searching in the wrong spot. That is for installed repositories. You need to add a new repository. See the HACS doco.

**Comment by ilium007** [comment]
No it isn't. See screenshot 'Add repository'

<img width="892" alt="image" src="https://user-images.githubusercontent.com/732766/133912221-9071f8a9-00bd-45d2-aa12-47c9a9e3b719.png">

**Comment by safepay** [comment]
I'm not a HACS expert. It's been in the repository for 2 years.
Can't help much more than that, sorry.

**Comment by ilium007** [comment]
Had to search for ‘safepay’. Got all the sensor data but having a hard time trying to follow the dark sky card directions.
