### ISSUE TITLE
 implements device_state_attributes. Please report it to the custom component author.

### ISSUE THREAD

**Issue by davros123** [safepay/sensor.willyweather#16]
I am sure your aware - but I thought I'd post anyway :) 

` Logger: homeassistant.helpers.entity
Source: helpers/entity.py:574
First occurred: 10:06:24 PM (54 occurrences)
Last logged: 10:07:07 PM

    Entity sensor.ww_day_6_min_temp (<class 'custom_components.willyweather.sensor.WWWeatherSensor'>) implements device_state_attributes. Please report it to the custom component author.
    Entity sensor.ww_day_6_rain (<class 'custom_components.willyweather.sensor.WWWeatherSensor'>) implements device_state_attributes. Please report it to the custom component author.
    Entity sensor.ww_day_6_rain_probability (<class 'custom_components.willyweather.sensor.WWWeatherSensor'>) implements device_state_attributes. Please report it to the custom component author.
    Entity sensor.ww_day_6_summary (<class 'custom_components.willyweather.sensor.WWWeatherSensor'>) implements device_state_attributes. Please report it to the custom component author.
    Entity sensor.ww_day_6_icon (<class 'custom_components.willyweather.sensor.WWWeatherSensor'>) implements device_state_attributes. Please report it to the custom component author.
`

**Comment by safepay** [comment]
No. If you could provide more information to assist, that would be useful.

What version of HA.
What is the config.

etc.
