### ISSUE TITLE
KeyError: 'observational'

### ISSUE THREAD

**Issue by jscooksey** [safepay/sensor.willyweather#18]
It doesnt appear to have hit the WillWeather server, as that shows no use still.
HA is showing this in the logs
Im digging around, but I thought I'd post this 
Home Assistant 2022.8.6
Frontend 20220802.0 - latest

Logger: homeassistant.components.sensor
Source: custom_components/willyweather/sensor.py:311
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 4:22:49 PM (1 occurrences)
Last logged: 4:22:49 PM

Error while setting up willyweather platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/willyweather/sensor.py", line 156, in setup_platform
    ww_data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 192, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/willyweather/sensor.py", line 311, in update
    self._data = result['observational']
KeyError: 'observational'

**Comment by safepay** [comment]
It's just configured wrong on WillyWeather API settings page. See the README.

**Comment by jscooksey** [comment]
Yeah, I removed station_id and I had quote marks around the API key that I removed.
I have entity values now.
Thank you

**Comment by hirani89** [comment]
Hi, I am having the same error. I have checked that the config on WillyWeather API settings page is correct. If I use the browser to make the call. All seems to be working.

`https://api.willyweather.com.au/v2/API_KEY/locations/13719/weather.json?observational=true`

And the result is
```
{
  "location": {
    "id": 13719,
    "name": "Scoresby",
    "region": "Melbourne",
    "state": "VIC",
    "postcode": "3179",
    "timeZone": "Australia/Melbourne",
    "lat": -37.8987,
    "lng": 145.2301,
    "typeId": 21
  },
  "observational": {
    "observations": {
      "temperature": {
        "temperature": 21.9,
        "apparentTemperature": 19.8,
        "trend": 1
      },
      "delta-t": {
        "temperature": 5.9,
        "trend": -1
      },
      "cloud": {
        "oktas": 0,
        "trend": 0
      },
      "humidity": {
        "percentage": 51,
        "trend": 1
      },
      "dewPoint": {
        "temperature": 11.3,
        "trend": 1
      },
      "pressure": {
        "pressure": 1019.6,
        "trend": 0
      },
      "wind": {
        "speed": 13,
        "gustSpeed": 20.4,
        "trend": 0,
        "direction": 190,
        "directionText": "S"
      },
      "rainfall": {
        "lastHourAmount": 0,
        "todayAmount": 1.2,
        "since9AMAmount": 0
      }
    },
    "stations": {
      "temperature": {
        "id": 441,
        "name": "Scoresby",
        "lat": -37.871,
        "lng": 145.256,
        "distance": 3.8
      },
      "delta-t": {
        "id": 441,
        "name": "Scoresby",
        "lat": -37.871,
        "lng": 145.256,
        "distance": 3.8
      },
      "cloud": {
        "id": 440,
        "name": "Moorabbin Airport",
        "lat": -37.98,
        "lng": 145.096,
        "distance": 14.8
      },
      "humidity": {
        "id": 441,
        "name": "Scoresby",
        "lat": -37.871,
        "lng": 145.256,
        "distance": 3.8
      },
      "dewPoint": {
        "id": 441,
        "name": "Scoresby",
        "lat": -37.871,
        "lng": 145.256,
        "distance": 3.8
      },
      "pressure": {
        "id": 440,
        "name": "Moorabbin Airport",
        "lat": -37.98,
        "lng": 145.096,
        "distance": 14.8
      },
      "wind": {
        "id": 441,
        "name": "Scoresby",
        "lat": -37.871,
        "lng": 145.256,
        "distance": 3.8
      },
      "rainfall": {
        "id": 441,
        "name": "Scoresby",
        "lat": -37.871,
        "lng": 145.256,
        "distance": 3.8
      }
    },
    "issueDateTime": "2024-02-26 13:20:00",
    "units": {
      "temperature": "c",
      "amount": "mm",
      "speed": "km/h",
      "distance": "km",
      "pressure": "hPa"
    }
  }
}
```
