### ISSUE TITLE
iOS/safari dates incorrect

### ISSUE THREAD

**Issue by matthew-larner** [safepay/sensor.willyweather#3]
The dates show perfectly on chrome. The issue is when browsing on the Home Assistant iOS app or safari, the dates show as "Invalid Date". The fix is to use the timestamp format "yyyy-mm-ddThh:mm:ss".

https://community.home-assistant.io/t/timestamp-cant-show-in-ios-app-but-working-on-chrome/102714

**Comment by safepay** [comment]
Thanks.

I have added a fix to the master branch.

Please confirm this is working.

**Comment by matthew-larner** [comment]
Awesome thanks! Confirmed that it's working ok.
