### ISSUE TITLE
"Conditions" icons missing on HA v 0.106.1

### ISSUE THREAD

**Issue by nickdos** [safepay/sensor.willyweather#5]
After upgrading to HA version 0.106.1, the icons next to the `sensor.bom_forecast_xxxxx_N` entries have disappeared. These are the icons which change, depending on the forecast conditions _ cloudy, raining, sunny, etc. The "static" icons are still showing, e.g. `WW Day 0 Rain` is OK.

**Comment by safepay** [comment]
sensor.bom_forecast_xxxxx_N 

Are you sure these are from the Willy Weather sensors or from another BoM integration?

**Comment by nickdos** [comment]
I think you're right. I commented out the forecast days option for this sensor and the forecast still shows data. Sorry about that.
