### ISSUE TITLE
Exceptional status for current weather

### ISSUE THREAD

**Issue by matthew-larner** [safepay/sensor.willyweather#7]
I'm seeing an 'exceptional' status for the current days weather. Screenshot of the issue: https://imgur.com/4OBREmF

**Comment by safepay** [comment]
That's normal.

There are only limited statuses in HA for weather. If it doesn't fit one, then it defaults to exceptional.

When the bushfires were around and there was smoke, I got exceptional on quite a few days because there is no "smoke" status.

**Comment by matthew-larner** [comment]
ah ok got it. Would it make sense to map them to something else? i.e. smoke -> cloudy or fog?

**Comment by safepay** [comment]
Yes. There are quite a few "missing" statuses, so we just have to map to what they allow.
