### ISSUE TITLE
IO errors inside event loop

### ISSUE THREAD

**Issue by sabbrowne** [safepay/sensor.willyweather#9]
Hi,
Just installed WillyWeather sensors from HACS and added the following to my configuration.yaml file. Should I be worried about this?
sensor weather:
  - platform: willyweather
    api_key: ??????????????????????????
Have not added frontend card yet
Running hassio v0.110.4
All sensors are listed and values in Developer Tools>States except the Dew Point. This is probably because its not available as a selection in API
-------------------------------------
Logger: homeassistant.util.async_
Source: util/async_.py:120
First occurred: June 1, 2020, 8:17:38 PM (31 occurrences)
Last logged: 10:58:57 AM

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for willyweather doing I/O at custom_components/willyweather/sensor.py, line 343: resp = requests.get(closestURL, params=closestURLParams, timeout=10).json()

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for willyweather doing I/O at custom_components/willyweather/sensor.py, line 299: result = requests.get(self._build_url(), timeout=10).json()

This is the API config for my account:
![image](https://user-images.githubusercontent.com/24983434/83470543-d195f600-a4c5-11ea-95e5-6da7f2613779.png)

Cheers

Shane

**Comment by sabbrowne** [comment]
Ill close this... A range of things do not work with this card and IO errors creating slow downs. Seems like not longer supported.

Cheers

**Comment by harrisony** [comment]
@sabbrowne Are you using the master release?

**Comment by safepay** [comment]
I still use it. Had no need to change it.
Not updated doesn't mean not supported, but the I/O stuff is beyond me.
If someone else wants to fix that, then go for it.

**Comment by harrisony** [comment]
@safepay it was actually fixed by #8 

It may be worth making a release to ensure people recieve the fix

**Comment by safepay** [comment]
Will do.

**Comment by safepay** [comment]
Release has been done to correct log errors.
